### ISSUE TITLE
Not picking up existing symbolic links, therefore not forcing sync

### ISSUE THREAD

**Issue by jackhulk** [ktheod/OneDriveBully#17]
Hello

Great looking app, thanks for sharing. Problem is that after adding my 'OneDrive Root Folder' and clicking 'Refresh', nope of my current symbolic links display and therefore force sync doesn't work. If I try to add symbolic link via app, it states "_You need to run the application as Administrator_" which I'm feel unease about doing and would rather not do.

Is there any way to get the app to recognize existing symbolic links, or add these via the app without running as administrator please?

Thank you

**Comment by jackhulk** [comment]
My bad, my apologizes. After I set the minutes (which I did do before), clicked 'Save' (didn't do before) and clicked refresh, the symbolic links then appeared. Question remains though, is it at all possible to add the symbolic links via the app without running it as administrator?

Also I noticed that the symbolic link folders and files within the OneDrive always have a status of syncing (two circled blue arrows), even though the sync is complete. Is just how it is with the links, or is it possible to have the status symbols to display correctly please?

**Comment by ktheod** [comment]
Hi jackhulk for your feedback. I don't think that you can create symlinks in Windows even by using cmd without running it as an administrator. The app just provides a simple GUI to help with creating the symlinks but essentially executes the same command.

Regarding the sync status, many people have mentioned this and I notice it too but unfortunately it is the way it is for the reason explained below:

ODB does only two things...1 provide a GUI for symlinks and settings, 2 periodically create/rename an empty file in the root folder of OneDrive. That's it...the empty file just tricks OneDrive to rescan and sync all changes even on symbolic folders. You could have the same result if you created the symlinks by using command prompt and every 10 minutes you created manually a file in OneDrive root folder. This app just puts everything together. :)

Hope that helps. Let me know if I can help with anything else.

**Comment by ktheod** [comment]
Hi jackhulk, in the new version 1.4 about to be released, creating symbolic links does not require to run the app as Administrator.
Thanks,
