### ISSUE TITLE
Does this work for symlinks of files, or only directories?

### ISSUE THREAD

**Issue by e-t-l** [ktheod/OneDriveBully#18]
I have two symlinks currently in my Onedrive, one pointing to a directory and one pointing to a single file. When I installed OneDriveBully, it identified the directory symlink no problem, but it doesn't recognize the file. Is this a hard limitation of OneDriveBully, a bug, or a feature that could be added? 

(Relatedly, does OneDriveBully work with hardlinks/junctions, or is it really _only_ symlinks?)

**Comment by ktheod** [comment]
Hi e-t-l, initially it was supporting only folder symlinks but with the contribution of user micahmo it now also supports junctions. 
It doesn't support single files for the reason explained below:

ODB does only two things...1 provide a GUI for symlinks and settings, 2 periodically create/rename an empty file in the root folder of OneDrive. That's it...the empty file just tricks OneDrive to rescan and sync all changes even on symbolic folders. You could have the same result if you created the symlinks by using command prompt and every 10 minutes you created manually a file in OneDrive root folder. This app just puts everything together. :)

Hope that helps. Let me know if I can help with anything else.

**Comment by e-t-l** [comment]
I understand. I have a hardlinked file in my OneDrive directory, so I'll see if it syncs over the next few days. If it does, then would it be possible to make the GUI include soft/hard-linked files?
