### ISSUE TITLE
64-bit portability

### ISSUE THREAD

**Issue by RobertoMarcelino** [ktheod/OneDriveBully#19]
This is not a problem. This is a question.

Microsoft is upgrading OneDrive to 64-bit.

Are there any plans to upgrade OneDrive Bully to 64-bit?

**Comment by ktheod** [comment]
Hi Roberto, 

OneDrive Bully doesn't have any link with OneDrive app.
The only way these two apps interact is by OneDrive Bully creating an empty file in OneDrive root folder to trigger the standard sync.

You can use OneDrive Bully for both x86 and x64 OneDrive.

Thanks,
