### ISSUE TITLE
Error When Running

### ISSUE THREAD

**Issue by GrantasticBeats** [ktheod/OneDriveBully#23]
Please see screenshot error for after just installing the Bully application. All I did was put in my OneDrive location and set the interval to 6 and this error popped up. I do not need to create symbolic links with this as I have already created all of the ones I need.

![image](https://user-images.githubusercontent.com/89787969/131347835-e47102e2-ab3a-4e44-acec-ee27a3294759.png)

**Comment by burnpsy** [comment]
I am having this same error. No clue what the cause is, this bug is present immediately.

**Comment by ktheod** [comment]
Hey both, this should be fixed in Release 1.4.

Thanks
