### ISSUE TITLE
Feature Request: Allow custom OneDrive Path for symlinks

### ISSUE THREAD

**Issue by Kered13** [ktheod/OneDriveBully#24]
Lately I've been frustrated by Google Drive removing core functionality that I rely on, and I'm at the end of my rope looking for an alternative. Your application is the closest I have found, it's only missing one small thing.

Here's what I want to do: I have two computers, my laptop and my desktop. I want to backup folders (Pictures and Documents) from both of them to OneDrive (or any cloud backup service really). I do _not_ want the folders synced across devices. I do _not_ want the folders moved to a different location on my filesystem. Your application handles all of this, but there's one issue: The folders on my laptop and desktop have the exact same path (C:\Users\Derek\Pictures, C:\Users\Derek\Documents). So regardless of which choice I choose when creating the symlink in OneDrive Bully, the OneDrive Path is the same.

What I would like is to define custom OneDrive Paths so that I can create something like OneDrive\Laptop\Pictures, OneDrive\Desktop\Pictures.

**Comment by ktheod** [comment]
Hi Kered13 and thanks for the request. 
Unfortunately OneDriveBully doesn't alter the standard OneDrive functionality. It simply triggers it by creating an empty text file in the root folder. 
You can achieve though what you described, if you set 2 folders on your Pictures and Documents folders "Laptop", "Desktop" and then change in your Desktop to not sync the Laptop folder and the opposite on your Laptop. 

Thanks
