### ISSUE TITLE
[feature request] Using USN journal for monitoring sync, and selective sync Feature!

### ISSUE THREAD

**Issue by MisteryMonster** [ktheod/OneDriveBully#25]
It could be better, when file actually change to trigger the synchronization! Seem monitoring file change could use USN Journal. Further, It would be nice to monitoring folder and automatically create new file symbolic link, the circumstance of this is like the folder structure i have:
```
-folder1
  -sync-me
    settings.conf
  -don't-sync
    some.logs
    some.lockfile
somthing.xml
```
when I don't want to sync `don't-sync` folder but remain the rest to sync, I could create a symlink structrue like this:
```
-OneDrive
  -folder1
    -sync-me
      settings.conf (symlink)
  some.logs (symlink)
```
But the new file create in `folder1` will not updated in OneDrive. So I think If OneDriveBully can automatically create a monitoring folder's newfile symbolic link (also ignore `don't-sync` folder) will be great!

**Comment by ktheod** [comment]
Hi MisteryMonster, thanks for the feedback. 
I don't have time to investigate in this change. If you want you can clone the repository and try to implement it. If it works I can merge it on the next release.

Thanks
