### ISSUE TITLE
VirusTotal false positive "Trojan.Malware.300983.susgen"

### ISSUE THREAD

**Issue by e-t-l** [ktheod/OneDriveBully#28]
VirusTotal flags this exe as a virus. Obviously I'm not worried about it, but it's good to avoid red flags if possible. Any ideas what's triggering this false positive, and whether it can be changed?

https://www.virustotal.com/gui/file/f0ac7e3d6b62fc7f3a48d7ab8e799d7866c14bbd360f9c0c822718c5da0b5bdd/detection

**Comment by ktheod** [comment]
Hi e-t-l. Thanks for the ticket, it is a false positive with VirusTotal. Checking the web it seems that many other people with VirusTotal had this for different apps which were safe. I can't reproduce the issue to identify what is causing it, so I will close the ticket for now and if you still have an issue please kindly raise a new ticket. 

Thanks
