### ISSUE TITLE
Please allow to add %USERPROFILE%\AppData folders

### ISSUE THREAD

**Issue by Rob-Negrete** [ktheod/OneDriveBully#3]
Hi,
 
As you may know, some apps save their data under AppData folders, mainly those that are installed from windows store. I have two examples: docker containers and ubuntu bash.

Regards.

**Comment by ktheod** [comment]
Hi Rob, 

can you check if you can create a symbolic link to any folder inside AppData ? I seem to be able to do so by browsing in C:\Users\<user name>\.AppData  folder and then Local, LocalLow, Roaming and their subfolders and create the symlinks in the same way as a normal folder.

![image](https://user-images.githubusercontent.com/20832437/50485403-107c6e00-09ed-11e9-8aee-42fd786a89a1.png)

Please be very careful though as these are system folders and are accessed/managed by the software vendors.. syncing invalid files from other computers may create issues with your apps. Do some tests with non critical AppData folders and if you feel certain then use it for more complicated cases.

Let me know if you have any issues with the above although as the app uses the standard MS symlink functionality, if the symlinks don't work with special folders like AppData there may not be something that can be done.

Hope the above make sense, merry xmas
