### ISSUE TITLE
Allow specifying bully interval in seconds or fractions of a minute

### ISSUE THREAD

**Issue by oskarkk** [ktheod/OneDriveBully#30]
When doing something on two computers with synced data or just testing the setup, interval like 30 or even 15 seconds would be much nicer than waiting a minute. If frequent bullying have considerable performance cost there could be some warning on setting interval at less than 1 minute (I haven't noticed any big resource usage, but I don't have many files on my drive right now).

**Comment by ktheod** [comment]
Hi Oskarkk, 

Thanks for ticket. Intervals of less than a minute would trigger OneDrive to scan all folders for changes while a previous scan for changes is still running. This would not be a realistic usage and may lead to unnecessary performance issues with OneDrive. 

If you just want to test a full sync earlier than the 1 minute timeout, you can always double click the icon to sync on demand.

Hope that helps.
