### ISSUE TITLE
Error when adding the folder to the "other" computer

### ISSUE THREAD

**Issue by WildFrogAlan** [ktheod/OneDriveBully#33]
So I am trying to find a way to get "C:\Users\Username\Appdata\Local\Google\Chrome\User Data" to synchronize between 2 computers so that when I add a profile on one computer it is replicated on the other computer. This way the shortcuts to the profiles on my computers desktops will direct to the exact same profile and stay in sync, including new profiles created on one computer but not the other. It is important for the shortcuts to point to the exact same folder as they are numbered and having a different number for the "same" profile on the other computer creates confusion and potentially duplicate shortcuts on the desktop. This tool is not allowing me to add the folder to the second computer "because it is already there".

![image](https://github.com/ktheod/OneDriveBully/assets/142933329/efe029bf-6717-45a9-ac27-5f48bbc2c8d3)

**Comment by ktheod** [comment]
Hi WildFrogAlan, thanks for the ticket and your comments. Apologies for the really long delay.
This should be fixed in version 1.4 coming out this weekend.
Thanks,
