### ISSUE TITLE
UI does not show up

### ISSUE THREAD

**Issue by meysconce** [ktheod/OneDriveBully#6]
hi i am using your latest version 1.2. was able to setup the msi and the UI opened once.  i  did link a  dropbox folder inside onedrive and worked well.
after exiting the application and when i reopen the UI does not show up. i tried uninstalling and reinstall stil the ui does not show up.

the task manager says that the process is running.
pls help to fix this.

**Comment by ktheod** [comment]
Hi both, I have added a Message shown when you close the application for the first time. 
This will be included in version 1.3
Thanks for your feedback.

![2021-02-16 22_59_35-OneDrive Bully](https://user-images.githubusercontent.com/20832437/108120990-c3672480-70aa-11eb-8f57-6cab5cd788d9.png)
