### ISSUE TITLE
more than one onedrive to sync

### ISSUE THREAD

**Issue by LordHumphrey** [ktheod/OneDriveBully#7]
I have two onedrive,but i cannot sync at the same time.My English not good,hope you can understand.

**Comment by ilikeballoons** [comment]
I am in the same situation, I have a personal onedrive and a 1tb one for university. I need to sync both independently but there's no way to do this with ODB currently. Maybe make it possible to have separate instances with separate config files?

**Comment by opicron** [comment]
+1 for linking symlinks to an specific onedrive folder

**Comment by quangkieu** [comment]
You could copy the Exe file to another folder and manually would run independently of the main one. Both could have different timer. If you need the auto start, add a shortcut to your "Startup" folder in Start Menu for the new exe
