### ISSUE TITLE
[Suggest] Using Temp folder as trigger

### ISSUE THREAD

**Issue by quangkieu** [ktheod/OneDriveBully#8]
As OneDrive also trigger of folder scan on folder creation, I would suggest to use temp folder so that OneDrive log would be more clean without the temp file fill up the history

**Comment by ktheod** [comment]
A fellow developer has suggested a possible solution of changing the functionality from create file - delete file, to renaming the existing file. I will investigate if Bully still works with this and hopefully the history log will not be spammed with the temp file. I will include it in the next release ;)

**Comment by ktheod** [comment]
I have updated the solution and will be included in the upcoming 1.3 release. Thanks for your feedback.
