### ISSUE TITLE
Great App!

### ISSUE THREAD

**Issue by dazeus123** [ktheod/OneDriveBully#9]
Great application! Works with ease!! Excelent support by the developer! Would recomend it!

**Comment by frostmute** [comment]
I also just want to say THANK YOU so much @ktheod. This simple, yet crucial, solution to what should have been addressed by the OD devs by now is invaluable.

**Comment by ktheod** [comment]
Thank you very much both of you, glad you enjoy the app. I had the same issue with OD and it was about time to create a solution :)
